service: default
runtime: python37

basic_scaling:
    max_instances: 4
    idle_timeout: 10m

resources:
    cpu: 8
    memory_gb: 16
    disk_size_gb: 10

entrypoint: gunicorn -t 600 -b 0.0.0.0:8050 main:server